### PR TITLE
feat: Add unit-tests

### LINKED ISSUE #18: Add unit-testing for search, functions and fetching
This will help when deploying new versions as well as help others contribute.

### PR DESCRIPTION
**Pull request by timharek**
Currently work in progress.

- Added tests for:
  - `caching.ts`
  - `nrk.ts`
  - `rss.ts` (only one new test)
- Fixed "bad" types in `test-utils.ts`.
- Moved `utils.ts` to `./lib`.
- Added test task.
- Added CI step for linting, formatting, type-checking and testing (via GitHub Actions).
- Fixed filename path in `generate-types.ts`.
- Added `Response`-function helpers for JSON and XML responses.
- Improved type-safety for `caching.ts`.

Closes #18

### CODE REVIEW

**Comment by olaven** [comment]
@timharek Great start! I'm attempting to decouple the RSS generation code as part of #23. I think I'll have a draft shortly. I'll leave the API code untouched, so this should not be impacted, but I thought I'd give a heads up regardless.

**Comment by timharek** [comment]
@olaven do you see any more tests that need to be added? 💭

**Comment by timharek** [comment]
> Assign me as reviewer whenever you feel ready

Not sure if you got notified, @olaven 😅

**Comment by olaven** [comment]
> > Assign me as reviewer whenever you feel ready
> 
> Not sure if you got notified, @olaven 😅

I did, I've just been busy! But thank you for reminding me regardless :) Will hopefully have a look this evening.

**Review by olaven — APPROVED** [review]
Great job! 💪

**Pull request merged**
