### PR TITLE
Upgrade Fresh and add a bunch of small QOL improvements

### PR DESCRIPTION
**Pull request by timharek**
Thank you for this great project!

I have added some improvements and QOL improvements as well :blush:

- Added formatting rules in `deno.json`.
- Added helper-task in `deno.json` for checking types and formatting for all files.
- Removed `deno.lock` because it's not compatible with other architectures atm. The offical Deno Fresh [`deno.json`](https://github.com/denoland/fresh/blob/main/deno.json#L2) disables it.
- Upgraded Fresh to latest version.
- Ran `deno fmt` to format all files.
- Removed old type imports, unused imports.
- Fixed a bunch of bad imports.
- Used `export default` for `SeriesCard`.
- Fixed variable naming where Context was said to be an unused variable.
- Used `FreshContext` instead of deprecated `HandlerContext`.
- Cleaned up types
- Added fallback if an episode is missing (because it threw an type-error).
- Added `type="search"` for search-box.
- Added `TODO` for broken types.
- Added URL beside copy button for easy access in case JavaScript loads slow or is disabled in the browser.
- Added missing `alt`-tag for series image for a11y.
- Removed redundant tsconfig.json.

Please let me know if there is any questions or feedback, I'm happy to help!

### CODE REVIEW

**Comment by timharek** [comment]
cc @olaven 😇

**Comment by olaven** [comment]
> cc @olaven 😇

Thank you for pinging me, I somehow did not notice this before now. 
And thank you for your contribution as well as a good PR description of the changes! 

I will look through it.

**Review by olaven — APPROVED** [review]
These all look like sane (overdue :)) changes.
NRSS was built very quickly; these contributions are very welcome. 

Have you done any testing?

**Comment by olaven** [comment]
> Have you done any testing?
In other words, feel free to squash-merge as soon as you have verified that 1: the frontend works and 2: the RSS feeds are valid.

**Comment by timharek** [comment]
Thanks for the reply! I have tested it, and there are no discrepancies in the RSS-feeds and the frontend works when you search for the podcasts 😊 

I also upgraded Fresh again to the new release that came out today.

**Comment by timharek** [comment]
Also I can't do the merge, because I don't have the correct permissions.

This is what I get with `gh`:
```bash
gh pr merge -sd
GraphQL: timharek does not have the correct permissions to execute `MergePullRequest` (mergePullRequest)
```

And I can't see the merge-button on the PR-page.

cc @olaven

**Comment by olaven** [comment]
> Also I can't do the merge, because I don't have the correct permissions.
> 
> This is what I get with `gh`:
> 
> ```shell
> gh pr merge -sd
> GraphQL: timharek does not have the correct permissions to execute `MergePullRequest` (mergePullRequest)
> ```
> 
> And I can't see the merge-button on the PR-page.
> 
> cc @olaven

My bad! I thought you could when the PR was approved by me. It's merged now. Thank you for your contribution! Welcome back :)

**Pull request merged**
